#!/bin/sh

for package in $(find /var/vcap/packages -type l -name 'toolbelt-*'); do
	for dir in bin sbin; do
		if [[ -d ${package}/${dir} ]]; then
			export PATH="${PATH}:${package}/${dir}"
		fi
	done
	for dir in lib; do
		if [[ -d ${package}/${dir} ]]; then
			if [[ -z ${LD_LIBRARY_PATH} ]]; then
				export LD_LIBRARY_PATH="${package}/${dir}"
			else
				export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${package}/${dir}"
			fi
		fi
	done
done


red=$(tput setaf 1)
green=$(tput setaf 2)
blue=$(tput setaf 4)
cyan=$(tput setaf 6)
rst=$(tput sgr0)
PS1="==[]=[ ${cyan}<%= spec.deployment %>${rst} ${green}<%= spec.job.name %>/<%= spec.index %>${rst} ]=[]=="
if [[ "${UID}" -eq 0 ]]; then
	PS1="$PS1\n\\t ${red}\\u${rst} ${blue}\\w\\e \$${rst} "
else
	PS1="$PS1\n\\t ${blue}\\u \\w #${rst} "
fi
export PS1="\[${PS1}\]"

<%= p('toolbelt.envrc') %>
